// <auto-generated />
namespace ye_olde_promptory_o_creatures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Birthday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Birthday));
        
        string IMigrationMetadata.Id
        {
            get { return "201611072313082_Birthday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
